spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/webhookinbox}
    username: ${DB_USER:webhookinbox}
    password: ${DB_PASSWORD:webhookinbox}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    cache: false
